# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ implementing-cd-pipeline ]
  pull_request:
    branches: [ implementing-cd-pipeline ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: gh-pages
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm audit --production
    - run: ./.github/workflows/tasks/deploy-gh-page.sh $GITHUB_TOKEN $GITHUB_USER $GITHUB_USER_EMAIL
      env:
        GITHUB_USER: ${{ secrets.GH_ACCESS_USER }}
        GITHUB_USER_EMAIL: ${{ secrets.GH_ACCESS_USER_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}